### PR TITLE
Customization for ImageCache needed

### PR DESCRIPTION
**Pull request by Dedrakot**
For long running application it is critical to have possibility to limit cache size or reload failed urls after some time. Add only old unlimited implementation because don't want to add some external dependencies. 
Right now I am using simple guava implementation. I can upload code if you intrested in. It's pretty the asme but failed urls stored in cache made with CacheBuilder.expireAfterWrite, base cache has limits based on number of images or on total size (CacheBuilder.maximumSize(size) or CacheBuilder.maximumWeight(weight).weigher(wegher))

### CODE REVIEW

**Comment by radkovo** [comment]
I like this solution of #26; I would merge this. However, could you please create a clean PR with the necessary changes only? Currently, half of the changed lines are just code formatting only which makes the PR very unclear. I understand that the coding style in CSSBox is not standard (for some historical reason) but this should not be solved in the same PR. Thanks!

**Comment by Dedrakot** [comment]
Sorry. I will make clean commits by tomorrow.

**Comment by Dedrakot** [comment]
Sorry. My bad. Do I need to put new files on the same code style? (It's ok, just need some time to configure code style in IDE)
Have some questions about code:
1) Are "toolkit.prepareImage" always works fine with null image? ContentImage::loadImage(boolean).
May be it is better to return null from caching section?
2) "while (imageReaders.hasNext())" in ContentImage::loadImageFromSource(URL) looks strange. As I understand if we have more then one ImageReader then we try to read image from same input stream several times.

**Comment by Dedrakot** [comment]
And one more thing. In this case we change default behavior. Becaues we not using cache by default. On first commit ([600b1d5](https://github.com/radkovo/CSSBox/pull/41/commits/600b1d586ad9eb2d11be7977f0b0c77911efc2e4)) I add fallback singleton. But then I remove it.

**Comment by Dedrakot** [comment]
Remembered the problem I was tring to achive earlier. Made loadImageFromSource not threw exception. Instead it returns null if something happen. It simplify code and fix problems which I made in previous commits.

**Comment by Dedrakot** [comment]
May be break from loop if image readed successfully will be a good idea. May be not.
<pre>
while (imageReaders.hasNext()) {
    ImageReader currentImageReader = imageReaders.next();
    currentImageReader.setInput(imageInputStream);
    currentImageReader.addIIOReadUpdateListener(this);
    try
    {
        image = currentImageReader.read(0);
        <b>break;</b>
    } catch (Exception e) {
        log.error("Image decoding error: " + e.getMessage() + " with reader " + currentImageReader);
    } finally {
        currentImageReader.dispose();
    }
}
</pre>

**Comment by radkovo** [comment]
Hi, you are right. I would suggest something like
```java
while (image == null && imageReaders.hasNext()) {
...
}
```
to avoid an unnecessary break.

The `toolkit.prepareImage()` should not be called for `null` images, this seems like a bug to me (but it is probably harmless anyway).

Regarding the formatting: my suggestion is, once you finish and test your changes, to create a new clean fork of the CSSBox master, add all the necessary changes (without reformatting the remaining code) and then make a commit (and PR). The purpose is to keep the history of changes clear so that it is possible to find modified lines when some bug appears. Currently, the commit history of your PR seems to be quite unreadable because of many formatting changes. Many thanks!

**Comment by Dedrakot** [comment]
Sorry it takes me too long to get here. Yeah Intellij Idea remove some spaces in comments and after the closing braces. At least now they must stay as they were before my commit.

**Comment by radkovo** [comment]
Great, this looks very reasonable. Merged. Thanks!

**Pull request merged**
