### PR TITLE
Added rendering-hints to increase quality of content-image.

### PR DESCRIPTION
**Pull request by eduardoejp**

### CODE REVIEW

**Comment by radkovo** [comment]
Thanks for the PR, it looks nice. Just for consistency: should we do the same for background images in [BackgroundImage](https://github.com/radkovo/CSSBox/blob/master/src/main/java/org/fit/cssbox/layout/BackgroundImage.java#L112) class?

**Comment by eduardoejp** [comment]
> Thanks for the PR, it looks nice. Just for consistency: should we do the same for background images in BackgroundImage class?

I did do that in a (slightly) more updated version of CSSBox I'm using locally.

I made the change since I'm rendering some HTML that involves some PNG icons in some places and they are coming out kinda jagged (I assume due to aliasing).

The trick in this pull-request didn't help, anyway.

I'm working on figuring how to get them to look the right way, but if you've experience something similar to my problem before and have some tips, I'd be happy to hear them.

**Comment by radkovo** [comment]
Current implementation of image decoding is based on Toolkit and it makes many problems (e.g. some images are not properly at all). I am not sure if this is the reason of the low image quality but using ImageIO instead of Toolkit could bring better results. I can take look on that but it may take some time since I am quite busy now.

**Comment by radkovo** [comment]
Closing as obsolete (ImageIO is now being used).

**Pull request closed without merging**
